const fs = require('fs');
const path = require('path');

// Two products come out of one source tree:
//
//   --target=web    -> public/       the Vercel site, unchanged from before
//   --target=native -> native/       what Capacitor packs into the APK
//
// They differ in two ways. Size: the APK cannot carry pdf/ (134 MB) or the
// generated blog, so the native build simply doesn't copy them and fetches
// those bytes from the live site instead. Policy: Play forbids selling digital
// goods outside Play Billing, so every price, buy button and bKash number has
// to be *absent* from the APK, not merely hidden — a reviewer unzips the
// bundle. Markup is therefore cut at build time (see stripMarkers), and so is
// the purchase code itself (see stripJsMarkers) — but only whole, self-contained
// top-level assignments, and the result is parse-checked before it is written.
// Everything else stays gated at runtime on IS_NATIVE, because regex-surgery on
// a 4,300-line global-scope file is how you ship a syntax error.

const target = (process.argv.find(a => a.startsWith('--target=')) || '--target=web').split('=')[1];
if (target !== 'web' && target !== 'native') {
    console.error(`Unknown --target "${target}". Use --target=web or --target=native.`);
    process.exit(1);
}
const isNative = target === 'native';

const outName = isNative ? 'native' : 'public';
const distDir = path.join(__dirname, outName);

console.log(`Building Ruqyah Audio App [target: ${target}] -> ${outName}/`);

if (fs.existsSync(distDir)) {
    console.log(`Cleaning existing ${outName} folder...`);
    fs.rmSync(distDir, { recursive: true, force: true });
}
fs.mkdirSync(distDir, { recursive: true });

// Regions of index.html wrapped in
//     <!-- #web-only --> ... <!-- /#web-only -->
// are cut from the native build, and vice versa for #native-only. An opening
// marker may carry a trailing comment explaining itself, so the pattern only
// anchors on the tag name.
function stripMarkers(html, tag) {
    const re = new RegExp(`<!--\\s*#${tag}\\b[\\s\\S]*?<!--\\s*/#${tag}\\s*-->`, 'g');
    return html.replace(re, '');
}

function buildHtml(srcFile, destFile) {
    let html = fs.readFileSync(path.join(__dirname, srcFile), 'utf8');
    const before = html.length;
    html = stripMarkers(html, isNative ? 'web-only' : 'native-only');
    fs.writeFileSync(path.join(distDir, destFile), html);
    const saved = before - html.length;
    console.log(`Built ${srcFile} -> ${outName}/${destFile}` + (saved ? ` (stripped ${(saved / 1024).toFixed(1)} KB)` : ''));
}

// The web root must be the marketing page, but Vercel checks the filesystem
// before it applies rewrites — a public/index.html would always beat the
// /app -> /app.html rewrite. So on web the landing page IS index.html and the
// app moves to app.html.
//
// The APK has no marketing page at all: index.html is the app itself. That
// removes the landing->app redirect flash on cold start, and keeps every price
// and bKash section in landing.html out of the bundle entirely.
if (isNative) {
    buildHtml('index.html', 'index.html');
} else {
    buildHtml('landing.html', 'index.html');
    buildHtml('index.html', 'app.html');
}

// Read by app.js before anything else runs, so IS_NATIVE is known at load.
fs.writeFileSync(
    path.join(distDir, 'build-flags.js'),
    `// Generated by build.js — do not edit.\nwindow.BUILD_TARGET = ${JSON.stringify(target)};\n`
);
console.log(`Wrote ${outName}/build-flags.js (BUILD_TARGET=${target})`);

// The JS counterpart of stripMarkers. Regions of app.js wrapped in
//     /* #web-only */ ... /* /#web-only */
// are cut from the native build. Only ever wrap complete top-level statements —
// a marker that starts inside a function or a template literal produces broken
// output — and note that the result is fed to new Function() below, so a
// mistake fails the build here rather than at runtime on someone's phone.
function stripJsMarkers(js, tag) {
    const re = new RegExp(`/\\*\\s*#${tag}\\b[\\s\\S]*?/\\*\\s*/#${tag}\\s*\\*/`, 'g');
    return js.replace(re, '');
}

function buildJs(srcFile, destFile) {
    let js = fs.readFileSync(path.join(__dirname, srcFile), 'utf8');
    const before = js.length;
    js = stripJsMarkers(js, isNative ? 'web-only' : 'native-only');
    if (js.length !== before) {
        // Parse, do not execute: new Function compiles the body and throws a
        // SyntaxError on malformed output, without touching the DOM globals
        // app.js expects.
        try {
            new Function(js);
        } catch (err) {
            console.error(`\n❌ ${srcFile} does not parse after marker stripping: ${err.message}`);
            console.error('   A /* #web-only */ region probably opens or closes mid-statement.');
            process.exit(1);
        }
    }
    fs.writeFileSync(path.join(distDir, destFile), js);
    const saved = before - js.length;
    console.log(`Built ${srcFile} -> ${outName}/${destFile}` + (saved ? ` (stripped ${(saved / 1024).toFixed(1)} KB)` : ''));
}

buildJs('app.js', 'app.js');

const filesToCopy = [
    'audio.json',
    'pdf_list.json',
    'service-worker.js',
    'firebase-config.js',
    'privacy.html',   // Play Store requires a reachable privacy policy URL
];

// The payment numbers live in their own file so they can be withheld from the
// APK outright rather than merely left unreferenced in it.
if (!isNative) filesToCopy.push('payments.js', 'features.html');

filesToCopy.forEach(name => {
    const src = path.join(__dirname, name);
    if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(distDir, name));
        console.log(`Copied ${name}`);
    } else {
        console.warn(`Warning: ${name} not found in root.`);
    }
});

// The manifest is one source file, but the app lives at a different path in
// each target: /app.html on the web (the root is the marketing page) and the
// root itself in the APK.
{
    const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8'));
    if (isNative) {
        manifest.id = '/';
        manifest.start_url = './';
    }
    fs.writeFileSync(path.join(distDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
    console.log(`Built manifest.json (start_url ${manifest.start_url})`);
}

function copyDirSync(src, dest) {
    fs.mkdirSync(dest, { recursive: true });
    for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) copyDirSync(srcPath, destPath);
        else fs.copyFileSync(srcPath, destPath);
    }
}

// Local launcher/PWA artwork. These used to be hotlinked from icons8, which
// meant the installed app had no icon offline and nothing usable for the store.
const iconsSrc = path.join(__dirname, 'icons');
if (fs.existsSync(iconsSrc)) {
    copyDirSync(iconsSrc, path.join(distDir, 'icons'));
    console.log('Copied icons/');
} else {
    console.warn('Warning: icons/ not found — run `node tools/make_placeholder_icons.js`.');
}

// Self-hosted webfonts, so Bengali renders correctly on a first offline launch.
const fontsSrc = path.join(__dirname, 'fonts');
if (fs.existsSync(fontsSrc)) {
    copyDirSync(fontsSrc, path.join(distDir, 'fonts'));
    console.log('Copied fonts/');
} else {
    console.warn('Warning: fonts/ not found — run `node tools/fetch_fonts.js`.');
}

// pdf.js. Goes into both targets: Android WebView cannot render a PDF at all,
// and desktop browsers disagree about how an <iframe> PDF behaves.
//
// cmaps/ (1.4 MB) is web-only. It matters for CID-keyed fonts, in practice CJK,
// which these guides do not use — so rather than carry it in the APK, app.js
// points cMapUrl at the website for the rare PDF that needs it. standard_fonts/
// ships in both because a PDF that references Helvetica without embedding it is
// ordinary, and that must work offline.
const pdfjsSrc = path.join(__dirname, 'vendor', 'pdfjs');
if (fs.existsSync(pdfjsSrc)) {
    const pdfjsDest = path.join(distDir, 'vendor', 'pdfjs');
    fs.mkdirSync(pdfjsDest, { recursive: true });
    for (const entry of fs.readdirSync(pdfjsSrc, { withFileTypes: true })) {
        if (isNative && entry.name === 'cmaps') continue;
        const from = path.join(pdfjsSrc, entry.name);
        const to = path.join(pdfjsDest, entry.name);
        if (entry.isDirectory()) copyDirSync(from, to);
        else fs.copyFileSync(from, to);
    }
    console.log(`Copied vendor/pdfjs/${isNative ? ' (without cmaps)' : ''}`);
} else {
    console.warn('Warning: vendor/pdfjs/ not found — run `node tools/fetch_pdfjs.js`.');
}

if (isNative) {
    // Everything below is web-only: the blog and the SEO catalogue pages exist
    // for crawlers, and the PDFs are streamed from the live site by the in-app
    // reader. Bundling them was what pushed the old build to 390 MB.
    console.log('Skipping blog, SEO catalogue and pdf/ — native build streams those.');
} else {
    // Blog: posts/*.md -> public/blog/<slug>/index.html (+ JSON the app reads)
    require('./tools/blog').buildBlog(distDir);

    // Crawlable catalogue pages for the audio library and PDF guides, which
    // otherwise exist only inside app.html's JavaScript where no crawler sees them.
    require('./tools/library').buildLibrary(distDir);

    const pdfSrc = path.join(__dirname, 'pdf');
    if (fs.existsSync(pdfSrc)) {
        console.log('Copying pdf directory recursively to public/pdf...');
        copyDirSync(pdfSrc, path.join(distDir, 'pdf'));
    } else {
        console.warn('Warning: pdf directory not found in root.');
    }
}

function dirSize(dir) {
    let total = 0;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name);
        total += entry.isDirectory() ? dirSize(p) : fs.statSync(p).size;
    }
    return total;
}

const sizeMb = dirSize(distDir) / (1024 * 1024);
console.log(`✅ Build completed — ${outName}/ is ${sizeMb.toFixed(1)} MB`);

// Play's ceiling is 200 MB for an AAB and the whole point of the native target
// is to stay nowhere near it. Fail loudly rather than discover this at upload.
if (isNative && sizeMb > 20) {
    console.error(`\n❌ native/ is ${sizeMb.toFixed(1)} MB — expected well under 20 MB.`);
    console.error('   Something large is being copied into the APK bundle again.');
    process.exit(1);
}
