// Downloads the three web fonts into fonts/ and writes fonts/fonts.css.
//
// They used to be loaded from fonts.googleapis.com at runtime. That meant a
// network round trip on every cold start, Bengali falling back to a system font
// on the first offline launch, and — because the stylesheet URL sat in the
// service worker's precache list — a failed install taking offline support with
// it. Inside the APK there is no reason to reach out at all.
//
//   node tools/fetch_fonts.js
//
// Google serves different files per User-Agent; the modern-browser UA below
// gets woff2. Only the unicode ranges the app actually needs are kept.

const fs = require('fs');
const path = require('path');
const https = require('https');

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// latin-ext is deliberately excluded: it covers Central/Eastern European
// diacritics this app never renders, and for Inter it costs 83 KB per weight —
// a third of the whole font payload for nothing.
const FAMILIES = [
    { css: 'Inter:wght@400;600;700;800', keep: ['latin'] },
    { css: 'Hind+Siliguri:wght@400;600;700', keep: ['bengali', 'latin'] },
    { css: 'Amiri:wght@400;700', keep: ['arabic', 'latin'] },
];

const OUT = path.join(__dirname, '..', 'fonts');

function get(url, headers = {}) {
    return new Promise((resolve, reject) => {
        https.get(url, { headers: { 'User-Agent': UA, ...headers } }, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                return get(res.headers.location, headers).then(resolve, reject);
            }
            if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
            const chunks = [];
            res.on('data', (c) => chunks.push(c));
            res.on('end', () => resolve(Buffer.concat(chunks)));
        }).on('error', reject);
    });
}

(async () => {
    fs.mkdirSync(OUT, { recursive: true });
    let out = '/* Generated by tools/fetch_fonts.js — do not edit. */\n';
    let files = 0, bytes = 0;

    for (const fam of FAMILIES) {
        const css = (await get(`https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`)).toString();

        // Google emits one @font-face per (family, weight, unicode subset),
        // each preceded by a /* subset */ comment.
        const blocks = css.split('/*').slice(1);
        for (const raw of blocks) {
            const subset = raw.slice(0, raw.indexOf('*/')).trim();
            if (!fam.keep.includes(subset)) continue;
            const block = raw.slice(raw.indexOf('*/') + 2);

            const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
            const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
            const weight = block.match(/font-weight:\s*(\d+)/)?.[1] || '400';
            const style = block.match(/font-style:\s*(\w+)/)?.[1] || 'normal';
            const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
            if (!url || !family) continue;

            const name = `${family.replace(/\s+/g, '-')}-${weight}-${style}-${subset}.woff2`;
            const buf = await get(url);
            fs.writeFileSync(path.join(OUT, name), buf);
            files++; bytes += buf.length;

            out += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};`
                 + `font-display:swap;src:url(${name}) format('woff2');`
                 + (range ? `unicode-range:${range};` : '')
                 + '}\n';
            console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)} KB`);
        }
    }

    fs.writeFileSync(path.join(OUT, 'fonts.css'), out);
    console.log(`\n${files} files, ${(bytes / 1024).toFixed(0)} KB total -> fonts/`);
})().catch((e) => { console.error('failed:', e.message); process.exit(1); });
